services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DB_URL=sqlite3:/app/ui.db
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/page/home"]
      interval: 3s
      timeout: 2s
      retries: 40

