name: Recording
on:
  workflow_dispatch:
  push:
    paths: [ 'demo/**', 'Dockerfile.app', 'docker-compose.yml', 'src/**', 'shard.yml' ]

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & record
        run: |
          docker compose up --build -d app
          # Wait for health (max ~90s)
          for i in {1..30}; do
            if curl -fsS http://localhost:3000/page/home > /dev/null; then break; fi
            sleep 3
          done
          docker compose run --rm recorder
      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: demo-recordings
          path: demo/recordings/**
